# Generated by Django 6.0.1 on 2026-01-28 06:48

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('original_image', models.ImageField(upload_to='uploads/')),
                ('face_detected', models.BooleanField(default=False)),
                ('visual_analysis', models.JSONField(blank=True, null=True)),
                ('chatbot_responses', models.JSONField(blank=True, null=True)),
                ('final_risk_level', models.CharField(blank=True, choices=[('GREEN', 'Low Risk'), ('YELLOW', 'Moderate Risk'), ('RED', 'High Risk')], max_length=10, null=True)),
                ('combined_score', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
